name: Build CI
on: [push, pull_request]
jobs:
  build:
    name: Java ${{ matrix.java }} test build
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2016, windows-2019, macos-10.15 ]
        java: [ 8, 9, 10, 11, 12, 13, 14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build mod
        run: gradle build
      - name: Package mod
        run: gradle jar